(include_subdirs unqualified)

(library
 (name language)
 (modules
  typ
  syntax
  holeSyntax
  holeSubstitution
  holeSyntaxUnify
  syntaxUtil
  holeSyntaxUtil
  syntaxPretty
  holeSyntaxPretty
  syntaxEqual
  cilBridge
  syntaxChecker
  holeSyntaxChecker
  location
  value
  valueOp
  memory
  typeUtil
  bigStep
  bigStepUtil
  bigStepChecker
  derivator
  size
  visualizer)
 (libraries goblint-cil pretty))
